name: Deploy to Hostinger VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.82.25.110.214 }}
        username: ${{ secrets.srv768796.hstgr.cloud }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /deployment/website/sdc-website
          git pull origin main
          npm install
          npm run build
          sudo systemctl restart nginx