export const faculty = [
    {
        id: 1,
        fullName: 'Professor (Dr.) Sandeep Chaurasia',
        designation: 'Director, Training & Placement CSE',
        email: 'sandeep.chaurasia@jaipur.manipal.edu',
        contact_number: '+91 9571228110',
        linkedin: 'https://www.linkedin.com/in/sandeep-chaurasia-0457568a/',
        profile_picture: '/profile-images/faculty/Sandeep-Chaurasia.jpeg',
    },
    {
        id: 2,
        fullName: 'Professor (Dr.) Neha Chaudhary',
        designation: 'Head of Department',
        email: 'chaudhary.neha@jaipur.manipal.edu',
        contact_number: '+91 9785500056',
        linkedin: 'https://www.linkedin.com/in/dr-neha-chaudhary-2b02bb31/',
        profile_picture: '/profile-images/faculty/Neha-Chaudhary.jpeg',
    },
    {
        id: 3,
        fullName: 'Dr Amit Garg',
        designation: 'Associate Professor',
        email: 'amit.garg@jaipur.manipal.edu',
        contact_number: '+91 9897260563',
        linkedin: 'https://www.linkedin.com/in/dr-amit-garg-87461637/',
        profile_picture: '/profile-images/faculty/Amit-Garg.jpeg',
    },
    {
        id: 4,
        fullName: 'Dr Sakshi Shringi',
        designation: 'Assistant Professor',
        email: 'sakshi.shringi@jaipur.manipal.edu',
        contact_number: '+91 9649832226',
        linkedin: 'https://www.linkedin.com/in/dr-sakshi-shringi-8082922b/',
        profile_picture: '/profile-images/faculty/Sakshi-Shringi.jpg',
    },
    {
        id: 5,
        fullName: 'Dr Shishir Singh Chauhan',
        designation: 'Assistant Professor (Senior Scale)',
        email: 'shishir.chauhan@jaipur.manipal.edu',
        contact_number: '+91 7905307175',
        linkedin: 'https://www.linkedin.com/in/shishir-chauhan-b888b2129/',
        profile_picture: '/profile-images/faculty/SHISHIR-SINGH.jpg',
    },
    // {
    //     id: 6,
    //     fullName: 'Dr Juhi Singh',
    //     designation: 'Assistant Professor (Selection Grade)',
    //     email: 'juhi.singh@jaipur.manipal.edu',
    //     contact_number: '+91 9717105742',
    //     linkedin: 'https://www.linkedin.com/in/dr-juhi-singh-171a4873/',
    //     profile_picture: '/profile-images/faculty/Juhi-Singh.jpg',
    // },
    {
        id: 7,
        fullName: 'Dr Prakash Ramani',
        designation: 'Professor',
        email: 'prakash.ramani@jaipur.manipal.edu',
        contact_number: '+91 8905987166',
        linkedin: 'https://www.linkedin.com/in/prakash-ramani-b73b58170/',
        profile_picture: '/profile-images/faculty/Prakash-Ramani.jpg',
    },
    {
        id: 8,
        fullName: 'Dr Mahesh Jangid',
        designation: 'Associate Professor',
        email: 'mahesh.jangid@jaipur.manipal.edu',
        contact_number: '+91 9799969068',
        linkedin: 'https://www.linkedin.com/in/mahesh-jangid/',
        profile_picture: '/profile-images/faculty/Mahesh-Jangid.jpg',
    },
    {
        id: 9,
        fullName: 'Dr Mayank Namdev',
        designation: 'Assistant Professor',
        email: 'mayank.namdev@jaipur.manipal.edu',
        contact_number: '+91 9826377765',
        linkedin: 'https://www.linkedin.com/in/dr-mayank-namdev-0175029/',
        profile_picture: '/profile-images/faculty/Mayank-Namdev.jpg',
    },
    {
        id: 10,
        fullName: 'Dr Rishi Gupta',
        designation: 'Associate Professor',
        email: 'rishi.gupta@jaipur.manipal.edu',
        contact_number: '+91 7976085813',
        linkedin: 'https://www.linkedin.com/in/rishi-gupta-7b8a3726/',
        profile_picture: '/profile-images/faculty/Rishi-Gupta.jpg',
    },
    {
        id: 11,
        fullName: 'Dr. Dibakar Sinha',
        designation: 'Assistant Professor (Senior Scale)',
        email: 'dibakar.sinha@jaipur.manipal.edu',
        contact_number: '+91 7507531275',
        linkedin: 'https://www.linkedin.com/in/dibakar-sinha-ph-d-b388b6a/',
        profile_picture: '/profile-images/faculty/Dibakar-Sinha.jpg',
    },
    {
        id: 12,
        fullName: 'Mr. Jay Shankar Sharma',
        designation: 'Assistant Professor',
        email: 'jay.sharma@jaipur.manipal.edu',
        contact_number: '',
        linkedin: 'https://www.linkedin.com/in/jay-shankar-sharma-294828107/',
        profile_picture: '/profile-images/faculty/Jay-Shankar-Sharma.jpg',
    },
];