export const students = [
    {
        id: 1,
        fullName: 'Jatin Kumar',
        year: '2024',
        project_code: 'PROJ01',
        Position_in_Team: 'Student Project Manager',
        Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 2,
        fullName: 'Priyanshu Sharma',
        year: '2025',
        project_code: 'PROJ01',
        Position_in_Team: 'Student Project Lead',
         Role: '',
       linkedin: 'https://www.linkedin.com/in/priyanshu-creed/',
        profile_picture: '/profile-images/students/Priyanshu-Sharma.jpeg',
    },
    {
        id: 3,
        fullName: 'Aryan Garg',
        year: '2025',
        project_code: 'PROJ01',
        Position_in_Team: 'Student Developer',
        Role: 'Flutter Developer',
        linkedin: 'https://www.linkedin.com/in/aryan-garg-muj',
         profile_picture: '/profile-images/students/Aryan-Garg.png',
    },
    {
        id: 4,
       fullName: 'Samaksh Gupta',
        year: '2027',
        project_code: 'PROJ01',
        Position_in_Team: 'Student Developer',
        Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
     {
        id: 5,
        fullName: 'Ashish Gupta',
         year: '2024',
        project_code: 'PROJ02',
        Position_in_Team: 'Student Project Manager',
        Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 6,
       fullName: 'Aditya Punmiya',
        year: '2025',
         project_code: 'PROJ02',
        Position_in_Team: 'Student Project Lead',
         Role: 'Backend Developer',
        linkedin: 'https://www.linkedin.com/in/aditya-punmiya-077b47229/',
        profile_picture: '/profile-images/students/Aditya-Punmiya.jpg',
    },
    {
        id: 7,
        fullName: 'Shikhar Maheshwari',
        year: '2025',
        project_code: 'PROJ02',
        Position_in_Team: 'Student Developer',
          Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 8,
        fullName: 'Abraham V George',
        year: '2025',
        project_code: 'PROJ02',
        Position_in_Team: 'Student Developer',
          Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
     {
        id: 9,
        fullName: 'Chandransh Srivastava',
        year: '2025',
         project_code: 'PROJ02',
        Position_in_Team: 'Student Developer',
         Role: 'Full Stack Developer',
        linkedin: 'https://www.linkedin.com/in/chandransh',
       profile_picture: '/profile-images/students/Chandransh-Srivastava.png',
    },
     {
        id: 10,
        fullName: 'Hiya Ghosh',
        year: '2025',
        project_code: 'PROJ02',
        Position_in_Team: 'Student Developer',
        Role: 'Frontend Developer',
        linkedin: 'https://www.linkedin.com/in/hiya-ghosh-484299260/',
       profile_picture: '/profile-images/students/Hiya-Ghosh.jpg',
    },
    {
        id: 11,
        fullName: 'Aman Kumar',
        year: '2025',
        project_code: 'PROJ02',
        Position_in_Team: 'Student Developer',
          Role: 'App Developer',
        linkedin: 'https://www.linkedin.com/in/aman-kumar-646502236/',
       profile_picture: '/profile-images/students/Aman-Kumar.jpg',
    },
     {
        id: 12,
        fullName: 'Suyash Srivastava',
       year: '2026',
        project_code: 'PROJ02',
        Position_in_Team: 'Student Developer',
          Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
         id: 13,
        fullName: 'Nirmal',
        year: '2026',
        project_code: 'PROJ02',
       Position_in_Team: 'Student Developer',
        Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 14,
         fullName: 'Tushar Baweja',
        year: '2027',
       project_code: 'PROJ02',
        Position_in_Team: 'Student Developer',
         Role: '',
       linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 15,
        fullName: 'Abhay Tripathi',
        year: '2025',
       project_code: 'PROJ03',
        Position_in_Team: 'Student Project Lead',
        Role: 'Full Stack Developer',
        linkedin: 'https://linkedin.com/in/abhaytri/',
         profile_picture: '/profile-images/students/Abhay-Tripathi.jpg',
    },
     {
         id: 16,
         fullName: 'Agam Bhasin',
         year: '2027',
        project_code: 'PROJ03',
       Position_in_Team: 'Student Developer',
          Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 17,
        fullName: 'Abhay Tripathi',
        year: '2025',
         project_code: 'PROJ04',
       Position_in_Team: 'Student Project Lead',
         Role: 'Full Stack Developer',
         linkedin: 'https://linkedin.com/in/abhaytri/',
        profile_picture: '/profile-images/students/Abhay-Tripathi.jpg',
    },
    {
       id: 18,
        fullName: 'Gokul Bansal',
        year: '2025',
         project_code: 'PROJ04',
        Position_in_Team: 'Student Developer',
        Role: 'Full Stack Developer',
        linkedin: 'https://www.linkedin.com/in/gokul-bansal-553429225/',
        profile_picture: '/profile-images/students/Gokul-Bansal.jpg',
    },
    {
       id: 19,
       fullName: 'Drishti Singh',
        year: '2025',
         project_code: 'PROJ04',
        Position_in_Team: 'Student Developer',
         Role: 'Frontend Developer',
        linkedin: 'https://www.linkedin.com/in/drishti-singh-bb9bb0223',
         profile_picture: '/profile-images/students/Drishti-Singh.jpg',
    },
    {
         id: 20,
        fullName: 'Garv Kundnani',
        year: '2027',
        project_code: 'PROJ04',
       Position_in_Team: 'Student Developer',
          Role: '',
       linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 21,
       fullName: 'Chehak Miglani',
        year: '2026',
        project_code: 'PROJ04',
        Position_in_Team: 'Student Developer',
          Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 22,
        fullName: 'Abhijaat Pandey',
        year: '2025',
       project_code: 'PROJ05',
        Position_in_Team: 'Student Project Lead',
         Role: 'Full Stack Developer',
       linkedin: 'https://in.linkedin.com/in/abhijaat-pandey-078942260',
        profile_picture: '/profile-images/students/Abhijaat-Pandey.png',
    },
    {
        id: 23,
         fullName: 'Arsh Kasid',
        year: '2025',
       project_code: 'PROJ05',
        Position_in_Team: 'Student Developer',
         Role: 'Back-End developer',
        linkedin: 'https://www.linkedin.com/in/arsh-kasid-a799821bb',
         profile_picture: '/profile-images/students/Arsh-Kasid.jpg',
    },
     {
        id: 24,
        fullName: 'Shivang Verma',
        year: '2025',
         project_code: 'PROJ05',
        Position_in_Team: 'Student Developer',
          Role: 'Full Stack Developer',
        linkedin: 'https://www.linkedin.com/in/shivangverma26/',
       profile_picture: '/profile-images/students/Shivang-Verma.jpg',
    },
    {
       id: 25,
       fullName: 'Het Gandhi',
        year: '2025',
        project_code: 'PROJ05',
       Position_in_Team: 'Student Developer',
        Role: 'Full Stack Developer',
        linkedin: 'https://www.linkedin.com/in/het-gandhi-33a019169/',
       profile_picture: '/profile-images/students/Het-Gandhi.jpg',
    },
    {
       id: 26,
       fullName: 'Krish Sharma',
       year: '2027',
        project_code: 'PROJ05',
        Position_in_Team: 'Student Developer',
          Role: '',
       linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 27,
        fullName: 'Yashi Shree',
        year: '2026',
        project_code: 'PROJ05',
        Position_in_Team: 'Student Developer',
          Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 28,
        fullName: 'Lakshay',
        year: '2024',
        project_code: 'PROJ06',
        Position_in_Team: 'Student Project Manager',
        Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 29,
        fullName: 'Tanay',
        year: '2024',
       project_code: 'PROJ06',
       Position_in_Team: 'Student Project Manager',
         Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 30,
       fullName: 'Samarth Bagga',
        year: '2025',
        project_code: 'PROJ06',
        Position_in_Team: 'Student Project Lead',
        Role: 'Front End Developer',
        linkedin: 'https://www.linkedin.com/in/samarth-bagga-175453226/',
        profile_picture: '/profile-images/students/Samarth-Bagga.jpg',
    },
    {
        id: 31,
        fullName: 'Dibek Todi',
        year: '2025',
       project_code: 'PROJ06',
       Position_in_Team: 'Student Developer',
        Role: 'Flutter Developer',
        linkedin: 'www.linkedin.com/in/dibek-todi',
         profile_picture: '/profile-images/students/Dibek-Todi.jpeg',
    },
    {
        id: 32,
         fullName: 'Aryan Kamboj',
       year: '2025',
        project_code: 'PROJ06',
        Position_in_Team: 'Student Developer',
       Role: 'Full Stack Developer',
        linkedin: 'https://www.linkedin.com/in/aryan-kamboj-32873a215/',
        profile_picture: '/profile-images/students/Aryan-Kamboj.png',
    },
     {
        id: 33,
        fullName: 'Devashish Roy',
        year: '2025',
         project_code: 'PROJ06',
        Position_in_Team: 'Student Developer',
          Role: 'Full Stack Developer',
        linkedin: 'https://www.linkedin.com/in/roy-devashish/',
       profile_picture: '/profile-images/students/Devashish-Roy.jpeg',
    },
    {
       id: 34,
       fullName: 'Sushruta Saptaputre',
        year: '2025',
        project_code: 'PROJ06',
        Position_in_Team: 'Student Developer',
          Role: 'Backend Developer',
        linkedin: 'www.linkedin.com/in/sushrut-saptaputre/',
        profile_picture: '/profile-images/students/Sushrut-Saptaputre.png',
    },
    {
        id: 35,
        fullName: 'Usha Mayuri Muppa',
        year: '2025',
       project_code: 'PROJ06',
       Position_in_Team: 'Student Developer',
         Role: 'IOS Developer',
        linkedin: 'https://www.linkedin.com/in/usha-mayuri-muppa-83b7a422a/',
        profile_picture: '/profile-images/students/Usha-Mayuri-Muppa.png',
    },
     {
        id: 36,
        fullName: 'Vidhi Behl',
       year: '2026',
       project_code: 'PROJ06',
        Position_in_Team: 'Student Developer',
          Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 37,
       fullName: 'Nishit Tripathi',
        year: '2025',
       project_code: 'PROJ07',
       Position_in_Team: 'Student Project Lead',
          Role: 'Back-End Developer',
        linkedin: 'https://www.linkedin.com/',
        profile_picture: '/profile-images/students/Nishit-Tripathi.jpg',
    },
    {
       id: 38,
        fullName: 'Ishansh Tank',
        year: '2025',
        project_code: 'PROJ07',
        Position_in_Team: 'Student Developer',
        Role: 'Full Stack Developer',
        linkedin: 'https://www.linkedin.com/in/ishansh-taunk/',
        profile_picture: '/profile-images/students/Ishansh-Taunk.jpg',
    },
    {
        id: 39,
       fullName: 'Devanshu Kejriwal',
        year: '2025',
         project_code: 'PROJ07',
       Position_in_Team: 'Student Developer',
         Role: 'Frontend developer',
        linkedin: 'https://www.linkedin.com/in/devanshu-kejriwal/',
         profile_picture: '/profile-images/students/Devanshu-Kejriwal.jpg',
    },
    {
       id: 40,
       fullName: 'Shreshth Purohit',
       year: '2026',
         project_code: 'PROJ07',
       Position_in_Team: 'Student Developer',
        Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
         id: 41,
        fullName: 'Vivek Kumar Garg',
       year: '2027',
       project_code: 'PROJ07',
        Position_in_Team: 'Student Developer',
         Role: '',
       linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
       id: 42,
        fullName: 'Vinayak Kumawat',
        year: '2025',
        project_code: 'PROJ08',
        Position_in_Team: 'Student Project Lead',
       Role: 'Full Stack Developer',
        linkedin: 'https://www.linkedin.com/in/vinayakkumawat/',
        profile_picture: '/profile-images/students/Vinayak-Kumawat.png',
    },
     {
        id: 43,
        fullName: 'Ashi Malatya',
        year: '2025',
         project_code: 'PROJ08',
       Position_in_Team: 'Student Developer',
       Role: 'UX/UI Designer',
        linkedin: 'https://www.linkedin.com/in/ashi-malaiya-721b33220/',
        profile_picture: '/profile-images/students/Ashi-Malaiya.jpg',
    },
    {
        id: 44,
       fullName: 'Arya Ratan Mishra',
        year: '2025',
       project_code: 'PROJ08',
       Position_in_Team: 'Student Developer',
        Role: 'Front-End Developer',
         linkedin: 'https://www.linkedin.com/in/arya-ratan-b3a7681b3/',
        profile_picture: '/profile-images/students/Arya-Ratan.jpeg',
    },
    {
        id: 45,
       fullName: 'Preeti Khurana',
        year: '2025',
        project_code: 'PROJ08',
        Position_in_Team: 'Student Developer',
        Role: 'Frontend Developer',
        linkedin: 'https://www.linkedin.com/in/preetikhurana110',
        profile_picture: '/profile-images/students/Preeti-Khurana.png',
    },
    {
       id: 46,
        fullName: 'Gayathri Ravindran',
        year: '2027',
        project_code: 'PROJ08',
       Position_in_Team: 'Student Developer',
          Role: '',
        linkedin: 'https://www.linkedin.com/in/gayathri-ravindran/',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
        id: 47,
         fullName: 'Ishan Sharda',
        year: '2026',
        project_code: 'PROJ08',
        Position_in_Team: 'Student Developer',
          Role: '',
        linkedin: '',
        profile_picture: '/profile-images/students/blank-pfp.png',
    },
    {
       id: 48,
        fullName: 'Shivang Datta',
        year: '2025',
        project_code: 'PROJ09',
       Position_in_Team: 'Student Project Lead',
        Role: 'Full Stack Developer',
         linkedin: 'https://www.linkedin.com/in/shivang-datta-aa8127256/',
        profile_picture: '/profile-images/students/Shivang-Datta.png',
    },
    {
        id: 49,
        fullName: 'Jinit Bhatt',
        year: '2025',
        project_code: 'PROJ09',
        Position_in_Team: 'Student Developer',
       Role: 'Full Stack Developer',
         linkedin: 'https://www.linkedin.com/in/jinit-bhatt-989527248/',
       profile_picture: '/profile-images/students/Jinit-Bhatt.jpg',
    },
    {
         id: 50,
        fullName: 'Yahya Aseerullah',
        year: '2025',
        project_code: 'PROJ09',
        Position_in_Team: 'Student Developer',
         Role: 'Backend Developer',
        linkedin: 'https://www.linkedin.com/in/yahya-aseerullah/',
       profile_picture: '/profile-images/students/Yahya-Aseerullah.jpg',
    },
     {
         id: 51,
        fullName: 'Jitendra Choudhary',
       year: '2025',
        project_code: 'PROJ10',
        Position_in_Team: 'Student Project Lead',
         Role: 'Full Stack Developer',
        linkedin: 'https://www.linkedin.com/in/jitendra-choudhary-24544b242',
        profile_picture: '/profile-images/students/Jitendra-Choudhary.jpeg',
    },
    {
        id: 52,
        fullName: 'Guneet Pahwa',
        year: '2024',
        project_code: '',
        Position_in_Team: '',
        Role: 'UI/UX Designer',
        linkedin: 'https://www.linkedin.com/in/guneet-pahwa-350063264',
        profile_picture: '/profile-images/students/Guneet-Pahwa.jpeg',
    },
];