export const studentLeadership = {
  director: {
    fullName: "Preet Kulkarni",
    year: "2025",
    Role: "Student Director",
    linkedin: "https://www.linkedin.com/in/preet-kulkarni-2453ab284/",
    profile_picture: "/profile-images/students/Preet-Kulkarni.jpeg",
  },
  coordinators: [
    {
      fullName: "Position Open",
      year: "",
      Role: "Student Coordinator",
      linkedin: "#",
      profile_picture: "/profile-images/students/blank-pfp.png",
    },
    {
      fullName: "Position Open",
      year: "",
      Role: "Student Coordinator",
      linkedin: "#",
      profile_picture: "/profile-images/students/blank-pfp.png",
    },
  ],
};

export const students = [
  // SDC Website Team (PROJ08)
  {
    id: 42,
    fullName: "Vinayak Kumawat",
    year: "2024",
    project_code: "PROJ08",
    Position_in_Team: "Student Project Lead",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/vinayakkumawat/",
    profile_picture: "/profile-images/students/Vinayak-Kumawat.png",
  },
  {
    id: 47,
    fullName: "Ishan Sharda",
    year: "2025",
    project_code: "PROJ08",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/ishan-pramod-sharda-8b0b6012b/",
    profile_picture: "/profile-images/students/Ishan-Sharda.jpeg",
  },
  {
    id: 46,
    fullName: "Gayathri Ravindran",
    year: "2025",
    project_code: "PROJ08",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/gayathri-ravindran/",
    profile_picture: "/profile-images/students/Gayathri-Ravindran.jpeg",
  },
  {
    id: 78,
    fullName: "Abhiman Panwar",
    year: "2025",
    project_code: "PROJ08",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/abhiman-panwar-272aa7228/",
    profile_picture: "/profile-images/students/Abhiman-Panwar.jpeg",
  },
  {
    id: 60,
    fullName: "Lakshya Varshney",
    year: "2025",
    project_code: "PROJ08",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/lakshya-varshney-2b1855267/",
    profile_picture: "/profile-images/students/Lakshya-Varshney.jpeg",
  },
  {
    id: 43,
    fullName: "Ashi Malatya",
    year: "2024",
    project_code: "PROJ08",
    Position_in_Team: "Student Developer",
    Role: "UX/UI Designer",
    linkedin: "https://www.linkedin.com/in/ashi-malaiya-721b33220/",
    profile_picture: "/profile-images/students/Ashi-Malaiya.jpg",
  },
  {
    id: 44,
    fullName: "Arya Ratan Mishra",
    year: "2024",
    project_code: "PROJ08",
    Position_in_Team: "Student Developer",
    Role: "Front-End Developer",
    linkedin: "https://www.linkedin.com/in/arya-ratan-b3a7681b3/",
    profile_picture: "/profile-images/students/Arya-Ratan.jpeg",
  },
  {
    id: 45,
    fullName: "Preeti Khurana",
    year: "2024",
    project_code: "PROJ08",
    Position_in_Team: "Student Developer",
    Role: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/preetikhurana110",
    profile_picture: "/profile-images/students/Preeti-Khurana.png",
  },

  // Rest of the students
  {
    id: 1,
    fullName: "Jatin Kumar",
    year: "2023",
    project_code: "PROJ01",
    Position_in_Team: "Student Project Manager",
    Role: "",
    linkedin: "http://linkedin.com/in/ladiesmen219/",
    profile_picture: "/profile-images/students/blank-pfp.png",
  },
  {
    id: 2,
    fullName: "Priyanshu Sharma",
    year: "2024", // Updated from 2025
    project_code: "PROJ01",
    Position_in_Team: "Student Project Lead",
    Role: "",
    linkedin: "https://www.linkedin.com/in/priyanshu-creed/",
    profile_picture: "/profile-images/students/Priyanshu-Sharma.jpeg",
  },
  {
    id: 3,
    fullName: "Aryan Garg",
    year: "2024", // Updated from 2025
    project_code: "PROJ01",
    Position_in_Team: "Student Developer",
    Role: "Flutter Developer",
    linkedin: "https://www.linkedin.com/in/aryan-garg-muj/",
    profile_picture: "/profile-images/students/Aryan-Garg.png",
  },
  {
    id: 4,
    fullName: "Samaksh Gupta",
    year: "2025", // Updated from 2027
    project_code: "PROJ01",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/samakshgupta04/",
    profile_picture: "/profile-images/students/Samaksh-Gupta.jpeg",
  },
  {
    id: 5,
    fullName: "Ashish Gupta",
    year: "2023",
    project_code: "PROJ02",
    Position_in_Team: "Student Project Manager",
    Role: "",
    linkedin: "http://linkedin.com/in/ashish-gupta-2002/",
    profile_picture: "/profile-images/students/Ashish-Gupta.jpeg",
  },
  {
    id: 6,
    fullName: "Aditya Punmiya",
    year: "2024", // Updated from 2025
    project_code: "PROJ02",
    Position_in_Team: "Student Project Lead",
    Role: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/aditya-punmiya-077b47229/",
    profile_picture: "/profile-images/students/Aditya-Punmiya.jpg",
  },
  {
    id: 7,
    fullName: "Shikhar Maheshwari",
    year: "2024", // Updated from 2025
    project_code: "PROJ02",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/shikhar-maheshwari/",
    profile_picture: "/profile-images/students/blank-pfp.png",
  },
  {
    id: 8,
    fullName: "Abraham V George",
    year: "2024", // Updated from 2025
    project_code: "PROJ02",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/abrahamvgeorge/",
    profile_picture: "/profile-images/students/Abraham-George.jpeg",
  },
  {
    id: 9,
    fullName: "Chandransh Srivastava",
    year: "2024", // Updated from 2025
    project_code: "PROJ02",
    Position_in_Team: "Student Developer",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/chandransh",
    profile_picture: "/profile-images/students/Chandransh-Srivastava.png",
  },
  {
    id: 10,
    fullName: "Hiya Ghosh",
    year: "2024", // Updated from 2025
    project_code: "PROJ02",
    Position_in_Team: "Student Developer",
    Role: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/hiya-ghosh-484299260/",
    profile_picture: "/profile-images/students/Hiya-Ghosh.jpg",
  },
  {
    id: 11,
    fullName: "Aman Kumar",
    year: "2024", // Updated from 2025
    project_code: "PROJ02",
    Position_in_Team: "Student Developer",
    Role: "App Developer",
    linkedin: "https://www.linkedin.com/in/aman-kumar-646502236/",
    profile_picture: "/profile-images/students/Aman-Kumar.jpg",
  },
  {
    id: 12,
    fullName: "Suyash Srivastava",
    year: "2025", // Updated from 2026
    project_code: "PROJ02",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/srivastava-suyash/",
    profile_picture: "/profile-images/students/Suyash-Srivastava.jpeg",
  },
  {
    id: 13,
    fullName: "Nirmal",
    year: "2025", // Updated from 2026
    project_code: "PROJ02",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/nirmal-rajkumar-629b46210/",
    profile_picture: "/profile-images/students/Nirmal.jpeg",
  },
  {
    id: 14,
    fullName: "Tushar Baweja",
    year: "2025", // Updated from 2027
    project_code: "PROJ02",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/tushar-baweja-13652226a/",
    profile_picture: "/profile-images/students/Tushar-Baweja.jpeg",
  },
  {
    id: 15,
    fullName: "Abhay Tripathi",
    year: "2024", // Updated from 2025
    project_code: "PROJ03",
    Position_in_Team: "Student Project Lead",
    Role: "Full Stack Developer",
    linkedin: "https://linkedin.com/in/abhaytri/",
    profile_picture: "/profile-images/students/Abhay-Tripathi.jpg",
  },
  {
    id: 16,
    fullName: "Agam Bhasin",
    year: "2025", // Updated from 2027
    project_code: "PROJ03",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "http://linkedin.com/in/bhasinagam/",
    profile_picture: "/profile-images/students/Agam-Bhasin.jpeg",
  },
  {
    id: 17,
    fullName: "Abhay Tripathi",
    year: "2024", // Updated from 2025
    project_code: "PROJ04",
    Position_in_Team: "Student Project Lead",
    Role: "Full Stack Developer",
    linkedin: "https://linkedin.com/in/abhaytri/",
    profile_picture: "/profile-images/students/Abhay-Tripathi.jpg",
  },
  {
    id: 18,
    fullName: "Gokul Bansal",
    year: "2024", // Updated from 2025
    project_code: "PROJ04",
    Position_in_Team: "Student Developer",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/gokul-bansal-553429225/",
    profile_picture: "/profile-images/students/Gokul-Bansal.jpg",
  },
  {
    id: 19,
    fullName: "Drishti Singh",
    year: "2024", // Updated from 2025
    project_code: "PROJ04",
    Position_in_Team: "Student Developer",
    Role: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/drishti-singh-bb9bb0223",
    profile_picture: "/profile-images/students/Drishti-Singh.jpg",
  },
  {
    id: 20,
    fullName: "Garv Kundnani",
    year: "2025", // Updated from 2027
    project_code: "PROJ04",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/garvkundnani/",
    profile_picture: "/profile-images/students/Garv-Kundnani.jpeg",
  },
  {
    id: 21,
    fullName: "Chehak Miglani",
    year: "2025", // Updated from 2026
    project_code: "PROJ04",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/chehak-miglani/",
    profile_picture: "/profile-images/students/Chehak-Miglani.jpeg",
  },
  {
    id: 22,
    fullName: "Abhijaat Pandey",
    year: "2024", // Updated from 2025
    project_code: "PROJ05",
    Position_in_Team: "Student Project Lead",
    Role: "Full Stack Developer",
    linkedin: "https://in.linkedin.com/in/abhijaat-pandey-078942260",
    profile_picture: "/profile-images/students/Abhijaat-Pandey.png",
  },
  {
    id: 23,
    fullName: "Arsh Kasid",
    year: "2024", // Updated from 2025
    project_code: "PROJ05",
    Position_in_Team: "Student Developer",
    Role: "Back-End developer",
    linkedin: "https://www.linkedin.com/in/arsh-kasid-a799821bb",
    profile_picture: "/profile-images/students/Arsh-Kasid.jpg",
  },
  {
    id: 24,
    fullName: "Shivang Verma",
    year: "2024", // Updated from 2025
    project_code: "PROJ05",
    Position_in_Team: "Student Developer",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/shivangverma26/",
    profile_picture: "/profile-images/students/Shivang-Verma.jpg",
  },
  {
    id: 25,
    fullName: "Het Gandhi",
    year: "2024", // Updated from 2025
    project_code: "PROJ05",
    Position_in_Team: "Student Developer",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/het-gandhi-33a019169/",
    profile_picture: "/profile-images/students/Het-Gandhi.jpg",
  },
  {
    id: 26,
    fullName: "Krish Sharma",
    year: "2025", // Updated from 2027
    project_code: "PROJ05",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/krishsharma0413/",
    profile_picture: "/profile-images/students/Krish-Sharma.jpeg",
  },
  {
    id: 27,
    fullName: "Yashi Shree",
    year: "2025", // Updated from 2026
    project_code: "PROJ05",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/yashi-shree-6b5b18267/",
    profile_picture: "/profile-images/students/Yashi-Shree.jpeg",
  },
  {
    id: 28,
    fullName: "Lakshay",
    year: "2023",
    project_code: "PROJ06",
    Position_in_Team: "Student Project Manager",
    Role: "",
    linkedin: "http://linkedin.com/in/lakshayjain19",
    profile_picture: "/profile-images/students/blank-pfp.png",
  },
  {
    id: 29,
    fullName: "Tanay",
    year: "2023",
    project_code: "PROJ06",
    Position_in_Team: "Student Project Manager",
    Role: "",
    linkedin: "http://linkedin.com/in/tan95t",
    profile_picture: "/profile-images/students/blank-pfp.png",
  },
  {
    id: 30,
    fullName: "Samarth Bagga",
    year: "2024", // Updated from 2025
    project_code: "PROJ06",
    Position_in_Team: "Student Project Lead",
    Role: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/samarth-bagga-175453226/",
    profile_picture: "/profile-images/students/Samarth-Bagga.jpg",
  },
  {
    id: 31,
    fullName: "Dibek Todi",
    year: "2024", // Updated from 2025
    project_code: "PROJ06",
    Position_in_Team: "Student Developer",
    Role: "Flutter Developer",
    linkedin: "www.linkedin.com/in/dibek-todi",
    profile_picture: "/profile-images/students/Dibek-Todi.jpeg",
  },
  {
    id: 32,
    fullName: "Aryan Kamboj",
    year: "2024", // Updated from 2025
    project_code: "PROJ06",
    Position_in_Team: "Student Developer",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/aryan-kamboj-32873a215/",
    profile_picture: "/profile-images/students/Aryan-Kamboj.png",
  },
  {
    id: 33,
    fullName: "Devashish Roy",
    year: "2024", // Updated from 2025
    project_code: "PROJ06",
    Position_in_Team: "Student Developer",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/roy-devashish/",
    profile_picture: "/profile-images/students/Devashish-Roy.jpeg",
  },
  {
    id: 34,
    fullName: "Sushruta Saptaputre",
    year: "2024", // Updated from 2025
    project_code: "PROJ06",
    Position_in_Team: "Student Developer",
    Role: "Backend Developer",
    linkedin: "www.linkedin.com/in/sushrut-saptaputre/",
    profile_picture: "/profile-images/students/Sushrut-Saptaputre.png",
  },
  {
    id: 35,
    fullName: "Usha Mayuri Muppa",
    year: "2024", // Updated from 2025
    project_code: "PROJ06",
    Position_in_Team: "Student Developer",
    Role: "IOS Developer",
    linkedin: "https://www.linkedin.com/in/usha-mayuri-muppa-83b7a422a/",
    profile_picture: "/profile-images/students/Usha-Mayuri-Muppa.png",
  },
  {
    id: 36,
    fullName: "Vidhi Behl",
    year: "2025", // Updated from 2026
    project_code: "PROJ06",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/vidhi-behl-699965224/",
    profile_picture: "/profile-images/students/Vidhi-Behl.jpeg",
  },
  {
    id: 37,
    fullName: "Nishit Tripathi",
    year: "2024", // Updated from 2025
    project_code: "PROJ07",
    Position_in_Team: "Student Project Lead",
    Role: "Back-End Developer",
    linkedin: "https://www.linkedin.com/",
    profile_picture: "/profile-images/students/Nishit-Tripathi.jpg",
  },
  {
    id: 38,
    fullName: "Ishansh Tank",
    year: "2024", // Updated from 2025
    project_code: "PROJ07",
    Position_in_Team: "Student Developer",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/ishansh-taunk/",
    profile_picture: "/profile-images/students/Ishansh-Taunk.jpg",
  },
  {
    id: 39,
    fullName: "Devanshu Kejriwal",
    year: "2024", // Updated from 2025
    project_code: "PROJ07",
    Position_in_Team: "Student Developer",
    Role: "Frontend developer",
    linkedin: "https://www.linkedin.com/in/devanshu-kejriwal/",
    profile_picture: "/profile-images/students/Devanshu-Kejriwal.jpg",
  },
  {
    id: 40,
    fullName: "Shreshth Purohit",
    year: "2025", // Updated from 2026
    project_code: "PROJ07",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/shreshth-purohit-62a918230/",
    profile_picture: "/profile-images/students/Shreshth-Purohit.jpeg",
  },
  {
    id: 41,
    fullName: "Vivek Kumar Garg",
    year: "2025", // Updated from 2027
    project_code: "PROJ07",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/vivek-kumar-garg-097677280/",
    profile_picture: "/profile-images/students/Vivek-Garg.jpeg",
  },
  {
    id: 48,
    fullName: "Shivang Datta",
    year: "2024", // Updated from 2025
    project_code: "PROJ09",
    Position_in_Team: "Student Project Lead",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/shivang-datta-aa8127256/",
    profile_picture: "/profile-images/students/Shivang-Datta.png",
  },
  {
    id: 49,
    fullName: "Jinit Bhatt",
    year: "2024", // Updated from 2025
    project_code: "PROJ09",
    Position_in_Team: "Student Developer",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/jinit-bhatt-989527248/",
    profile_picture: "/profile-images/students/Jinit-Bhatt.jpg",
  },
  {
    id: 50,
    fullName: "Yahya Aseerullah",
    year: "2024", // Updated from 2025
    project_code: "PROJ09",
    Position_in_Team: "Student Developer",
    Role: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/yahya-aseerullah/",
    profile_picture: "/profile-images/students/Yahya-Aseerullah.jpg",
  },
  {
    id: 51,
    fullName: "Jitendra Choudhary",
    year: "2024", // Updated from 2025
    project_code: "PROJ10",
    Position_in_Team: "Student Project Lead",
    Role: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/jitendra-choudhary-24544b242",
    profile_picture: "/profile-images/students/Jitendra-Choudhary.jpeg",
  },
  {
    id: 52,
    fullName: "Guneet Pahwa",
    year: "2023",
    project_code: "",
    Position_in_Team: "",
    Role: "UI/UX Designer",
    linkedin: "https://www.linkedin.com/in/guneet-pahwa-350063264",
    profile_picture: "/profile-images/students/Guneet-Pahwa.jpeg",
  },
  {
    id: 53,
    fullName: "Ayush Behera",
    year: "2025",
    project_code: "PROJ05",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/ayush-behera-7343a421b/",
    profile_picture: "/profile-images/students/Ayush-Behera.jpeg",
  },
  {
    id: 54,
    fullName: "Preet Kulkarni",
    year: "2025",
    project_code: "PROJ05",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/preet-kulkarni-2453ab284/",
    profile_picture: "/profile-images/students/Preet-Kulkarni.jpeg",
  },
  {
    id: 55,
    fullName: "Shivansh Srivastava",
    year: "2025",
    project_code: "PROJ06",
    Position_in_Team: "Student Developer New",
    Role: "",
    linkedin: "https://www.linkedin.com/in/shivanshs04/",
    profile_picture: "/profile-images/students/Shivansh-Srivastava.jpeg",
  },
  {
    id: 56,
    fullName: "Abhijeet Anand Jha",
    year: "2025",
    project_code: "PROJ06",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/abhijeet-anand-jha-b517b7249",
    profile_picture: "/profile-images/students/Abhijeet-Anand-Jha.jpeg",
  },
  {
    id: 57,
    fullName: "Sainyam Acharya",
    year: "2024",
    project_code: "PROJ07",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/sainyamacharya/",
    profile_picture: "/profile-images/students/Sainyam-Acharya.jpeg",
  },
  {
    id: 58,
    fullName: "Raaj Shekhar",
    year: "2024",
    project_code: "PROJ07",
    Position_in_Team: "Student Developer New",
    Role: "",
    linkedin: "https://www.linkedin.com/in/raaj-shekhar-0494b028b/",
    profile_picture: "/profile-images/students/RaaJ-Shekhar.jpeg",
  },
  {
    id: 59,
    fullName: "Krishanu Bujarbaruah",
    year: "2024",
    project_code: "PROJ07",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/krishanubujarbaruah/",
    profile_picture: "/profile-images/students/Krishanu-Bujarbaruah.jpeg",
  },
  {
    id: 61,
    fullName: "Gaurav Kumar",
    year: "2025",
    project_code: "PROJ12",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/gaurav-kumar-11615220a/",
    profile_picture: "/profile-images/students/Gaurav-Kumar.jpeg",
  },
  {
    id: 62,
    fullName: "Shivank Goel",
    year: "2025",
    project_code: "PROJ12",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/shivank--goel/",
    profile_picture: "/profile-images/students/Shivank-Goel.jpeg",
  },
  {
    id: 63,
    fullName: "Rudraksh Khera",
    year: "2025",
    project_code: "PROJ12",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/rudraksh-khera-10263b258/",
    profile_picture: "/profile-images/students/Rudraksh-Khera.jpeg",
  },
  {
    id: 64,
    fullName: "Manasveer Singh Basra",
    year: "2025",
    project_code: "PROJ12",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/manasveer-singh-basra-172524316/",
    profile_picture: "/profile-images/students/Manasveer-Singh-Basra.jpeg",
  },
  {
    id: 65,
    fullName: "Aayani Verma",
    year: "2025",
    project_code: "PROJ13",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/aayaniverma/",
    profile_picture: "/profile-images/students/Aayani-Verma.jpeg",
  },
  {
    id: 66,
    fullName: "Ritvik Singh",
    year: "2025",
    project_code: "PROJ13",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/",
    profile_picture: "/profile-images/students/blank-pfp.png",
  },
  {
    id: 67,
    fullName: "Anant Sharma",
    year: "2025",
    project_code: "PROJ13",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/anant-sharma-5ba41b293/",
    profile_picture: "/profile-images/students/Anant-Sharma.jpeg",
  },
  {
    id: 68,
    fullName: "C Krishna Ghrini",
    year: "2025",
    project_code: "PROJ13",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/ckrishnaghrini/",
    profile_picture: "/profile-images/students/C-Krishna-Ghrini.jpeg",
  },
  {
    id: 69,
    fullName: "Vaibhav Sharma",
    year: "2025",
    project_code: "PROJ14",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/vaibhav-sharma-b81453246/",
    profile_picture: "/profile-images/students/Vaibhav-Sharma.jpeg",
  },
  {
    id: 70,
    fullName: "Aaryan Naithani",
    year: "2025",
    project_code: "PROJ14",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/aaryan-naithani-7395ba229/",
    profile_picture: "/profile-images/students/Aaryan-Naithani.jpeg",
  },
  {
    id: 71,
    fullName: "Swaraj Mali",
    year: "2025",
    project_code: "PROJ15",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/swaraj-mali-567070254/",
    profile_picture: "/profile-images/students/blank-pfp.png",
  },
  {
    id: 72,
    fullName: "Lakshya Sharma",
    year: "2025",
    project_code: "PROJ15",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/",
    profile_picture: "/profile-images/students/blank-pfp.png",
  },
  {
    id: 73,
    fullName: "Harsh Kumar",
    year: "2025",
    project_code: "PROJ16",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/harshkumar1407/",
    profile_picture: "/profile-images/students/Harsh-Kumar.jpeg",
  },
  {
    id: 74,
    fullName: "Srivatsa Palepu",
    year: "2025",
    project_code: "PROJ16",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/srivatsa-palepu/",
    profile_picture: "/profile-images/students/Srivatsa-Palepu.jpeg",
  },
  {
    id: 75,
    fullName: "Hammad Shaikh",
    year: "2025",
    project_code: "PROJ16",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/hammad-shaikh1105/",
    profile_picture: "/profile-images/students/Hammad-Shaikh.jpeg",
  },
  {
    id: 76,
    fullName: "Mohit Solanki",
    year: "2025",
    project_code: "PROJ17",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/mohit-solanki-ms/",
    profile_picture: "/profile-images/students/blank-pfp.png",
  },
  {
    id: 77,
    fullName: "Vedic Varma",
    year: "2025",
    project_code: "PROJ06",
    Position_in_Team: "Student Developer",
    Role: "",
    linkedin: "https://www.linkedin.com/in/vedic-varma/",
    profile_picture: "/profile-images/students/Vedic-Varma.jpeg",
  },
];
