export const projects = [
  {
    id: 4,
    title: "Geofencing Attendance Management System",
    project_code: "PROJ01",
    type: "Mobile Application",
    tech_stack: "Flutter, NodeJS, PostgreSQL",
    year_created: "2023",
    faculty_mentor: "Dr. Amit Garg",
    industry_mentor: "Mr. Deepak TCS",
    poster: "/project-images/PROJ01/PROJ01-poster.png",
    description:
      "Introducing an innovative geofencing-based attendance management solution that simplifies tracking by creating virtual classroom boundaries. Students can effortlessly mark attendance using their mobile devices upon entering the designated area. The system ensures accurate records with precise timestamps and duration tracking, reducing manual effort and improving efficiency for educators.",
    tag: "",
    image: "/project-images/PROJ01/PROJ01-thumbnail.jpg",
    link: "https://youtu.be/ynfneSQwoQY",
  },
  {
    id: 5,
    title: "Notesheet Management System",
    project_code: "PROJ02",
    type: "Web Application",
    tech_stack:
      "HTML, CSS, JavaScript, React.js, Tailwind CSS, Express.js as back-end framework, JSON Web Tokens (JWT), PostgreSQL",
    year_created: "2023",
    faculty_mentor: "Dr. Amit Garg",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ02/PROJ02-poster.png",
    description:
      "The Note Sheet Management System is a platform designed to streamline the process of managing and tracking academic note sheets within an educational institution.",
    tag: "",
    image: "/project-images/PROJ02/PROJ02-thumbnail.png",
    link: "https://youtu.be/zKjyaYgKuH0",
  },
  {
    id: 8,
    title: "Project Allocation System",
    project_code: "PROJ05",
    type: "Web Application",
    tech_stack: "HTML, CSS, Javascript, PHP, SQL",
    year_created: "2023",
    faculty_mentor: "Dr. Prakash Ramani",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ05/PROJ05-poster.png",
    description:
      "The Project Allocation System is a web-based platform designed to streamline and automate the process of assigning faculty mentors to students for minor projects. By replacing the traditional manual approach, this system ensures fair, transparent, and efficient student-faculty allocations. ",
    tag: "",
    image: "/project-images/PROJ05/PROJ05-thumbnail.png",
    link: "https://youtu.be/qIJeU2Iw3kk",
  },
  {
    id: 11,
    title: "SDC Website",
    project_code: "PROJ08",
    type: "Web Application",
    tech_stack:
      "NextJs, TailwindCSS, Framer Motion, React Icons, Emails, ParticleJs, NodeJS",
    year_created: "2023",
    faculty_mentor: "Dr. Shishir Singh, Dr. Amit Garg",
    industry_mentor: "Mr. Shashank",
    poster: "/project-images/PROJ08/PROJ08-poster.jpg",
    description:
      "The SDC Website project aims to develop a dynamic online platform for the Software Development Centre (SDC) that enhances internal operations while fostering student success, collaboration, and innovation. The project's primary objectives include creating an engaging landing page to showcase the SDC's mission, vision, and current initiatives, implementing a robust project management system.",
    tag: "",
    image: "/project-images/PROJ08/PROJ08-thumbnail.jpg",
    link: "https://www.youtube.com/embed/4_BwcdMoyxU",
  },
  {
    id: 9,
    title: "MUJ Travel Buddy",
    project_code: "PROJ06",
    type: "Mobile Application",
    tech_stack: "React.js, Flutter, Swift, NodeJS, ExpressJS, MongoDB",
    year_created: "2023",
    faculty_mentor: "Dr. Amit Garg",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ06/PROJ06-poster.png",
    description:
      "MUJ Travel Buddy is a dynamic carpooling application tailored to the diverse needs of Manipal University Jaipur (MUJ) students and faculty alike. Beyond just students, teachers can also actively participate in creating or joining rides, fostering a sense of inclusivity and collaboration within the MUJ community. The platform simplifies the process of ride creation, allowing users to specify their travel details such as origin, destination, departure time, and available seats.",
    tag: "",
    image: "/project-images/PROJ06/PROJ06-thumbnail.jpeg",
    link: "https://youtu.be/5CLaJCGKUT0",
  },
  {
    id: 10,
    title: "Elective Subject Allocation Process",
    project_code: "PROJ07",
    type: "Web Application",
    tech_stack:
      "Typescript, React, Express, PostgreSQL",
    year_created: "2023",
    faculty_mentor: "Dr. Rishi Gupta",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ07/PROJ07-poster.png",
    description:
      "This is a software that allows management of electives for students and faculty, easing the allocation of electives across all departments for all types of electives such as flexi core, program elective, minor specialization.",
    tag: "",
    image: "/project-images/PROJ07/PROJ07-thumbnail.png",
    link: "https://youtu.be/InSnMeqvmmE",
  },
  {
    id: 7,
    title: "MUJ Maps",
    project_code: "PROJ04",
    type: "Web Application",
    tech_stack:
      "React.JS, HTML, CSS, JavaScript, Node.JS, Express.js, OpenStreet Maps, OSRM, MongoDB",
    year_created: "2023",
    faculty_mentor: "Dr. Sandeep Chaurasia, Dr. Sakshi Shringi",
    industry_mentor: "N/A",
    description: "MUJ Maps is a comprehensive navigation tool designed to help students, staff, and visitors easily locate facilities, departments, and key points of interest across the campus. With interactive features and real-time updates, it ensures seamless navigation and accessibility for all users.",
    tag: "",
    image: "/project-images/PROJ04/PROJ04-thumbnail.jpeg",
    link: "https://youtu.be/3pTh4hDHXPw",
  },
  {
    id: 12,
    title: "MUJ HUB (PORTAL)",
    project_code: "PROJ09",
    type: "Web Application",
    tech_stack: "HTML, CSS, JavaScript, GoogleAPIs, ReactJS, Nodejs, MongoDB",
    year_created: "2023",
    faculty_mentor: "Dr. Mahesh Jangid",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ09/PROJ09-poster.png",
    description: "The MUJ HUB portal serves as the central hub for all SDC projects, streamlining collaboration, communication, and resource sharing among teams. It aims to enhance efficiency and coordination by providing a unified platform for project management, updates, and networking within the SDC ecosystem.",
    tag: "",
    image: "/project-images/PROJ09/PROJ09-poster.png",
    link: "https://youtu.be/FQIa2vLtzWk",
  },
  {
    id: 13,
    title: "MUJ Learn-Hub",
    project_code: "PROJ10",
    type: "Web Application",
    tech_stack: "React.js, TailwindCSS, Node.js, Express.js, MongoDB",
    year_created: "2023",
    faculty_mentor: "Dr. Sandeep Chaurasia",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ10/PROJ10-poster.jpeg",
    description: "The MUJ Learn-Hub EdTech project is an innovative online platform for Manipal University Jaipur (MUJ) students and instructors, fostering collaborative learning and knowledge sharing. It offers access to video lectures covering diverse topics, encouraging active participation from all members of the university community. Instructors are empowered to share specialized content, serving as mentors, and enhancing the overall learning experience.",
    tag: "",
    image: "/project-images/PROJ10/PROJ10-thumbnail.jpeg",
    link: "https://youtu.be/M4iyVUQP2vo",
  },
  {
    id: 14,
    title: "Mentor-Mentee Management",
    project_code: "PROJ20",
    type: "Web Application",
    tech_stack: "NextJS, TailwindCSS, Framer motion, Nextjs API, NextAuth, JWT, Google Recaptcha v3, Nodemailer, axios API, Mongoose, MongoDB",
    year_created: "2024",
    faculty_mentor: "Dr. Amit Garg",
    industry_mentor: "N/A",
    poster: "/project-images/mentor-mentee-thumbnail.jpg", 
    description: "The primary objective of MentorLink is to automate the connection between mentors and mentees, simplifying the scheduling and reporting of meetings with just a tap. Our goal is to streamline the entire process for both mentors , mentees and administration, creating a seamless user experience and manage the overall process.",
    tag: "",
    image: "/project-images/mentor-mentee-thumbnail.jpg",
    link: "https://youtu.be/rISXt8ih6Lw",
  },
  {
    id: 15,
    title: "Library Management System",
    project_code: "PROJ11",
    type: "Web Application",
    tech_stack: "HTML, CSS, JavaScript, Laravel PHP, MySQL, phpMyAdmin",
    year_created: "2024",
    faculty_mentor: "Dr. Amit Garg",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ11/PROJ11-poster.jpg", 
    description: "The Library Management System, built with Laravel PHP, streamlines school library operations with ERP integration. It features book issuance, returns, category management, author tracking, and book listings, ensuring efficient and organized management for librarians.",
    tag: "",
    image: "/project-images/PROJ11/PROJ11-poster.jpg", 
    link: "https://youtu.be/trGCcBqSKkU",
  },
  {
    id: 16,
    title: "Communa",
    project_code: "PROJ19",
    type: "Web Application",
    tech_stack: "NextJS, Tailwind, RadixUI, Serverless NextJS routes, CF Workers, MongoDB, CF KV store",
    year_created: "2024",
    faculty_mentor: "Dr. Amit Garg",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ19/PROJ19-poster.png", 
    description: "Communa – A Community Engagement Platform for MUJ Students. This platform is designed to foster a sense of belonging and connection among students by providing a space for them to share their interests, hobbies, and activities.",
    tag: "",
    image: "/project-images/PROJ19/PROJ19-thumbnail.png", 
    link: "https://youtu.be/IZOd4SkEuW0",
  },
  {
    id: 17,
    title: "Pothole Detection System",
    project_code: "PROJ14",
    type: "Android Application",
    tech_stack: "Kotlin, Jetpack Compose, XML, Retrofit, Material Design, PostgreSQL, Custom API, Firebase Storage, YOLO, Firebase Realtime DB, Google Maps API, Git, GitHub, Android Studio, Google Colab",
    year_created: "2024",
    faculty_mentor: "Dr. Amit Garg",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ14/PROJ14-poster.png", 
    description: "Uses YOLOv8 model to detect potholes from images. PostgreSQL-based authentication with role-based access. Officers can submit pothole reports with image & location. View pothole reports and assign workers efficiently. Visualize pothole locations and worker routes. Track assigned potholes and update status. Fetch reports and monitor repair efficiency.",
    tag: "Research Project",
    image: "/project-images/PROJ14/PROJ14-thumbnail.jpg", 
    link: "https://youtu.be/7xO0hTeCbJM",
  },
  {
    id: 18,
    title: "MUJ CSE Chatbot",
    project_code: "PROJ13",
    type: "Web Application",
    tech_stack: "Kotlin, Jetpack Compose, XML, Retrofit, Material Design, PostgreSQL, Custom API, Firebase Storage, YOLO, Firebase Realtime DB, Google Maps API, Git, GitHub, Android Studio, Google Colab",
    year_created: "2024",
    faculty_mentor: "Dr. Amit Garg",
    industry_mentor: "N/A",
    poster: "/project-images/PROJ13/PROJ13-poster.png", 
    description: "The MUJ CSE Chatbot is an intelligent virtual assistant designed to provide students and faculty with quick access to essential information about Manipal University Jaipur’s Computer Science department. Developed as part of SDC PROJ13, this chatbot enhances user experience by offering real-time responses, event updates, academic queries, and campus-related assistance.",
    tag: "",
    image: "/project-images/PROJ13/PROJ13-thumbnail.jpg", 
    link: "https://youtu.be/vNPTQnfvQtE",
  },
];